<?php

namespace App\Services\LaravelExcel;

use App\Services\LaravelExcel\Maatwebsite\Excel\Concerns\Copyable;
use App\Services\LaravelExcel\Maatwebsite\Excel\Concerns\Printable;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use Maatwebsite\Excel\Concerns\WithCustomCsvSettings;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithProperties;
use Maatwebsite\Excel\Concerns\WithStrictNullComparison;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;

class BaseExport implements FromCollection, ShouldAutoSize, WithColumnWidths, WithCustomCsvSettings, WithCustomStartCell, WithEvents, WithHeadings, WithMapping, WithProperties, WithStrictNullComparison, WithTitle
{
    use Copyable, Exportable, Printable;

    protected array $resolvedColumns = [];

    protected array $finalHeadings = [];

    protected string $copyright;

    protected string $copyrightFull;

    protected string $title = 'Set your $title variable | Bizo';

    protected string $sheet_title = 'Set your $sheet_title variable';

    protected array $defaultColumns = ['id'];

    protected array $columnWidths = [];

    /**
     * Constructor.
     */
    public function __construct(
        protected Request $request
    ) {
        $this->request = $request;
        $this->resolvedColumns = $this->resolveColumns();
        $this->copyright = 'Bizo © ' . Carbon::now()->year;
        $this->copyrightFull = 'The data in this document is generated by ' . $this->copyright;
    }

    /**
     * Sizing columns per passed configuration.
     */
    public function columnWidths(): array
    {
        $columnWidths = $this->columnWidths;
        $config = [];

        foreach ($this->resolvedColumns as $key) {
            if (array_key_exists($key, $columnWidths)) {
                $config[chr(65 + array_search($key, $this->resolvedColumns))] = $columnWidths[$key];
            }
        }

        return $config;
    }

    public function getCsvSettings(): array
    {
        return [
            'delimiter' => chr(9),
        ];
    }

    public function title(): string
    {
        return $this->sheet_title;
    }

    public function properties(): array
    {
        return [
            'creator' => $this->copyright,
            'lastModifiedBy' => $this->copyright,
            'title' => $this->title,
            'description' => $this->copyrightFull,
        ];
    }

    public function startCell(): string
    {
        return 'A3';
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {

                $event->sheet->setCellValue('A1', $this->title);
                $event->sheet->setCellValue('A2', $this->copyrightFull);
                $lastCellInRow = $this->getLastCellInRow();
                $event->sheet->mergeCells('A1:' . $lastCellInRow . '1');
                $event->sheet->mergeCells('A2:' . $lastCellInRow . '2');
                $event->sheet->getStyle('A3:' . $lastCellInRow . '3')->applyFromArray([
                    'font' => [
                        'bold' => true,
                    ],
                ]);
                $event->sheet->getStyle('A1:' . $lastCellInRow . '2')->applyFromArray([
                    'alignment' => [
                        'horizontal' => 'center',
                    ],
                ]);
            },
        ];
    }

    /**
     * Get the headings.
     */
    public function headings(): array
    {
        $this->finalHeadings = array_map(fn ($column) => $this->defaultColumns[$column]['label'], $this->resolvedColumns);

        return $this->finalHeadings;
    }

    /**
     * Get the results' collection.
     */
    public function collection(): Collection
    {
        throw new \Exception('Method not implemented. Please implement the collection method in your export class.');
    }

    /**
     * Map the data rows.
     */
    public function map($item): array
    {
        $mapper = array_map(function ($column) use ($item) {
            return $item->{$column['key']};
        }, $this->defaultColumns);

        $result = [];

        foreach ($this->resolvedColumns as $key) {
            if (array_key_exists($key, $mapper)) {
                $result[$key] = $mapper[$key];
            }
        }

        return $result;
    }

    /**
     * Get the columns.
     */
    protected function resolveColumns(): array
    {
        $requestedColumns = $this->request->input('columns');

        if (empty($requestedColumns)) {
            $filteredColumns = array_filter($this->defaultColumns, function ($column) {
                return $column['isVisible'] && (! isset($column['isExcludedFromExport']) || ! $column['isExcludedFromExport']);
            });
            $filteredColumns = array_keys($filteredColumns);
        } else {
            $filteredColumns = array_keys(array_filter($this->defaultColumns, function ($column, $key) use ($requestedColumns) {
                return in_array($key, $requestedColumns) || ($column['includeAlways'] ?? false);
            }, ARRAY_FILTER_USE_BOTH));

            return $filteredColumns;
        }

        return $filteredColumns;
    }

    protected function getLastCellInRow(): string
    {
        $headingsCount = count($this->finalHeadings);

        return $this->getColumnName($headingsCount);
    }

    private function getColumnName(int $index): string
    {
        $columnName = '';

        while ($index > 0) {
            $index--;
            $columnName = chr($index % 26 + 65) . $columnName;
            $index = intval($index / 26);
        }

        return $columnName;
    }
}
